version: '3'
services:

  yumrepo:
    container_name: spike-yum-repo
    image: dgutierrez1287/yum-repo
    networks:
      - backend
    ports:
      - 8081:80
    volumes:
      - ${RPM_REPO_DIR:-/tmp/spike/yum-repo}:/repo

  aptrepo:
    container_name: spike-apt-repo
    image: dorowu/apt-repo-server
    networks:
      - backend
    ports:
      - 8082:80
    volumes:
      - ${DEB_REPO_DIR:-/tmp/spike/apt-repo}:/data

  centos:
    container_name: spike-centos
    command:
      - sleep
      - infinity
    image: centos:7
    networks:
      - backend

  debian:
    container_name: spike-debian
    command:
      - sleep
      - infinity
    image: debian:9
    networks:
      - backend

networks:
  backend:
